blog2/blog2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('coreblog.urls')),
    url(r'^admin/', admin.site.urls),
]

blog2/coreblog/urls.py
from django.conf.urls import url

from . import views

app_name = 'coreblog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^edit/(\d+)$', views.edit, name='edit'),
    url(r'^add/$', views.new, name='new')
]

blog2/coreblog/models.py
from django.db import models


class Record(models.Model):
    title = models.CharField('Название', max_length=255)
    text = models.TextField('Текст')
    pub_date = models.DateTimeField('Дата создания')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog2/coreblog/forms.py
from django import forms
from .models import Record


class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ('title', 'text',)

blog2/coreblog/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Record
from .forms import RecordForm
from django.http import HttpResponse
from django.utils import timezone


def index(request):
    records_list = Record.objects.all()
    context = {'records_list': records_list}
    return render(request, 'coreblog/main.html', context)


def detail(request, record_id):
    record = Record.objects.get(id=record_id)
    if 'delete' in request.GET:
        record.delete()
        return render(request, 'coreblog/main.html', {'records_list': Record.objects.all()})
    return render(request, 'coreblog/detail.html', {'record': record})


def edit(request, record_id):
    record = get_object_or_404(Record, pk=record_id)
    if request.method == "POST":
        form = RecordForm(request.POST, instance=record)
        if form.is_valid():
            rec = form.save(commit=False)
            rec.pub_date = timezone.now()
            rec.save()
            return render(request, 'coreblog/detail.html', {'record': record})
    else:
        form = RecordForm(instance=record)
    return render(request, 'coreblog/edit.html', {'form': form})


def new(request):
    if request.method == "POST":
        form = RecordForm(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            record.pub_date = timezone.now()
            record.save()
            return render(request, 'coreblog/detail.html', {'record': record})
    else:
        form = RecordForm()
    return render(request, 'coreblog/edit.html', {'form': form})

blog2/coreblog/templates/coreblog/detail.html
{% extends 'coreblog/main.html' %}
{% block main_content %}
    <form method="get">
    <div class="jumbotron">
        <h2>{{ record.title }}</h2>
        <p>{{ record.text }}</p>
        <p><strong>Дата публикации: </strong>{{ record.pub_date }}</p>
    </div>
        <p>
        <a href="/edit/{{ record.id }}" class="btn btn-lg btn-success">Редактировать статью</a>
        <button type="button" class="btn btn-lg btn-danger">Удалить запись</button>
        </p>
        <a href="/" class="btn btn-lg btn-primary">Вернуться на главную</a><br>
    </form>
{% endblock main_content%}

blog2/coreblog/templates/coreblog/edit.html
{% extends 'coreblog/main.html' %}
{% block main_content %}
    <div class="jumbotron">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-lg btn-success" type="submit">Сохранить</button>
        <a href="/" class="btn btn-lg btn-success">На главную</a>
    </form>
    </div>
{% endblock main_content%}

blog2/coreblog/templates/coreblog/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Блог статей</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

</head>
<body>
<div class="page-header">
    <h1 class="blog-title">Блог обо всем</h1>
</div>
{% block main_content %}
<h3>Перечень статей</h3>
{% if records_list %}
    <table class="table">
    <tr>
        <th>Номер статьи</th><th>Заголовок</th><th>Дата публикации</th>
    </tr>
        {% for record in records_list %}
            <tr>
                <td align="center">{{ record.id }}</td><td><a href="{%  url 'coreblog:detail' record.id %}">
                {{ record.title }}</a> </td> <td>{{ record.pub_date }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Статей нет</p>
{% endif %}
    <a class="btn btn-lg btn-success" href="/add" role="button">Добавить статью</a></span>
{% endblock main_content %}
</body>
</html>